services:
  dynamodb-local:
    extends:
      file: shared/dynamo.yml
      service: dynamodb-local
  dynamo-setup:
    extends:
      file: shared/dynamo.yml
      service: dynamo-setup
  alert-job:
    extends:
      file: alert-job/docker-compose.yml
      service: alert-job
  web:
    extends:
      file: web/docker-compose.yml
      service: web
  rie-proxy:
    extends:
      file: web/docker-compose.yml
      service: rie-proxy
