services:
  wind-alert:
    image: wind-alert:latest
    ports:
      - "9000:8080"
    entrypoint: ["/usr/local/bin/aws-lambda-rie", "./main"]
    env_file: .env
    environment:
      - LOCAL_MODE=true
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=eu-central-1
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8005:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
