services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports:
      - "8010:8000"

  dynamo-setup:
    image: amazon/aws-cli
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      AWS_REGION: eu-central-1
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/bash", "/scripts/create-tables.sh"]
