services:
  dynamodb-local:
    extends:
      file: ../shared/dynamo.yml
      service: dynamodb-local
  dynamo-setup:
    extends:
      file: ../shared/dynamo.yml
      service: dynamo-setup
  web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    entrypoint: ["/usr/local/bin/aws-lambda-rie", "./main"]
    ports:
      - "9080:8080"
    env_file:
      - .env
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000

  rie-proxy:
    build:
      context: ..
      dockerfile: web/Dockerfile.rie-proxy
    depends_on:
      - web
    environment:
      LAMBDA_RIE_URL: http://app:8080/2015-03-31/functions/function/invocations
    ports:
      - "8080:8080"
