networks:
  default:
    external: true
    name: wind-alert-net

services:
  app:
    image: wind-alert:latest
    entrypoint: ["/usr/local/bin/aws-lambda-rie", "./main"]
    ports:
      - "9080:8080"
    env_file:
      - .env
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000

  rie-proxy:
    image: wind-alert-rie-proxy:latest
    depends_on:
      - app
    environment:
      LAMBDA_RIE_URL: http://app:8080/2015-03-31/functions/function/invocations
    ports:
      - "8080:8080"
